---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="fedora" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "rRc42BAyY/nCUX6irj+GtI3+8KComFjPn+OnWsRKNVfS9hxwbMVgVIUF+VFbLC86NuVrnVIevo+bIR9fyNBeuGcBljhWUsu0wiMGV5kBlmhnUWfcLGUMSIKpM1B1b798qWpJ1Cru5xij81ZZCH+DbJlTEaGfsZjwAhfnh4GDfSZ6L9snKi/+JTvQ2DTnYGbSaDhufBhZaw6ElWZH07dj8PKKjlYLuPCjVKR4pioVNMOyMyZEccw736bXeQDvMBiim1c3kzgCIA5RaAKFlKUqqXLWKXxGfXTqLy1yedVntPTsMr9BSsYNiNJ1e/MMwZ/gyy6iBIxuvEkm7+AJSP6zPcOJCdRZJPkaKSzzr6GFJQlnN3Df1zZa7Eu3bvlf72zBaGE9yFGZFC3ANX/E1eES5Moyqh2GUHPKL3L761UCY80/fmUpmfyXZ/U8eOj/T54YBlnnet7f54dKeydyuuf0+E989NryoIo5ddUYaNvmlqh1PlIirG/PB6Wrcsu77fcpxehWtje4P5bcmU+djGqqerauzSe8dHJid178V5ueArwJ9lM9gxsopdfUwlaxv/P04fkBCgwjvVzljWchrI0EG3zCN26JJ66yPpeN5TyaUM6Tb/4twqXNNQy3U8v42tlqe5cBjGbar7Hr1WAOi74SGEcZ+7uklqupeF9Xx2UvuaE="
  email: false
