---

- name: test if tigervnc_username is set correctly
  assert:
    that:
      - tigervnc_username is defined
    quiet: yes

- name: test if tigervnc_groupname is set correctly
  assert:
    that:
      - tigervnc_groupname is defined
    quiet: yes

- name: test if tigervnc_password is set correctly
  assert:
    that:
      - tigervnc_password is defined
    quiet: yes

- name: test if tigervnc_user_exists is set correctly
  assert:
    that:
      - tigervnc_user_exists is defined
      - tigervnc_user_exists is boolean
    quiet: yes

- name: test if tigervnc_desktop_session is set correctly
  assert:
    that:
      - tigervnc_desktop_session is defined
    quiet: yes
