---
# handlers file for tigervnc

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart tigervnc
  service:
    name: "{{ tigervnc_service }}"
    state: restarted
    daemon_reload: yes
  when:
    - not ansible_check_mode | bool
